DESC ELECTION;



SELECT DISTINCT ST_NAME FROM ELECTION;

SELECT DISTINCT YEAR  FROM ELECTION ;



SELECT DISTINCT PARTYNAME FROM ELECTION;

SELECT DISTINCT CAND_SEX FROM ELECTION;

SELECT
    ST_NAME,
    "YEAR",
    PC_NO,
    PC_NAME,
    PC_TYPE,
    CAND_NAME,
    CAND_SEX,
    PARTYNAME,
    PARTYABBRE,
    TOTVOTPOLL,
    ELECTORS
FROM
    ELECTION
WHERE
    ST_NAME = 'VARCHAR2(50)';



--PERFORMANCE TUNING QUESTIONS

-- sql query to find the total count of female candidates participating in each year 
SELECT YEAR,COUNT(TOTVOTPOLL) 
  AS TOTAL_FEMALE 
    FROM ELECTION 
       WHERE CAND_SEX='F' 
        GROUP BY YEAR ;


-- WRITE A SQL QUERY TO FIND THE TOTAL CANDIDATES WHO PARTICIPATED IN THE ELECTION AT EACH STATE IN EACH YEAR
SELECT YEAR,ST_NAME,COUNT(CAND_NAME)
  AS TOTAL_CAND 
    FROM ELECTION 
       GROUP BY YEAR,ST_NAME ; 


-- WRITE A SQL QUERY TO FIND TOTAL VOTES BJP GOT IN EACH STATE IN THE YEAR 1987 
SELECT ST_NAME,
    TOTVOTPOLL AS TOTAL_VOTES                        --THE OUTPUT SHOWS NO ROWS SELECTED OR NO DATA IS FETCHED BECAUSE
       FROM ELECTION                                      -- ELECTION WAS NOT CONDUCTED IN THE YEAR 1987
          WHERE PARTYNAME='BJP' AND YEAR=1987;  


    --WRITE A SQL QUERY TO FIND TOTAL CANDIDATES WHO PARTICIPATED IN THE ELECTION IN EACH STATE IN THE YEAR 2004 
   
     SELECT ST_NAME ,COUNT(CAND_NAME)  
      AS TOTAL_VOTES 
        FROM ELECTION 
           WHERE YEAR= 2004 
            GROUP BY ST_NAME;  


     -- WRITE A SQL QUERY TO FIND WHAT ARE THE TOP 5 PARTIES THAT GOT THE MOST VOTES IN UTTAR PRADESH IN THE YEAR 2014

      SELECT PARTYNAME ,SUM(TOTVOTPOLL) AS 
          TOP_PARTIES 
            FROM ELECTION 
              WHERE ST_NAME='UTTAR PRADESH' AND YEAR=2014
                   GROUP BY PARTYNAME 
                     ORDER BY TOP_PARTIES DESC
                         FETCH FIRST 5 ROWS ONLY ;
                 
    select sum(totvotpoll) as Most_votes,PARTYABBRE
      from election                                              -- FOR THE GIVEN QUESTION THERE IS NO DATA GIVEN
        where st_name='Uttar Pradesh' and year=2014                       --IN THE TABLE TO FETCH THE RECORDS    
          group by partyabbre
            order by Most_votes desc
             fetch first 5 rows only;
             
             --EXTRA QUESTIONS

-- FIND THE TOTAL CANDIDATES WHO PARTICIPATED IN WEST BENGAL IN THE YEAR 2014 
 SELECT ST_NAME,COUNT(ELECTORS)
    AS TOTAL_CANDIDATES 
        FROM ELECTION 
         WHERE ST_NAME ='West Bengal' AND YEAR=2014              -- for this query data is not fetched because 
           GROUP BY ST_NAME 
            ORDER BY YEAR ASC ;                    --there is no data given about west bengal in the table

-- WRITE A SQL QUERY TO FIND TOTAL VOTES BJP GOT IN STATE ANDHRAPRADESH IN THE YEAR 1987 
SELECT ST_NAME,SUM(TOTVOTPOLL) AS TOTAL_VOTES 
   FROM ELECTION
       WHERE ST_NAME='Andhra Pradesh' AND YEAR=1987     -- election was not coNducted in the year 1987 
          GROUP BY ST_NAME 
              ORDER BY YEAR ASC ;

-- write a sql query to find the Total vote percentage of BJP get in goa state in the year 2003 
 SELECT ST_NAME,COUNT(TOTVOTPOLL) AS TOT_VOTE_PERCENTAGE                 
    FROM ELECTION 
        WHERE ST_NAME='Goa' AND YEAR=2003           -- no data given about state goa not given in the table
           GROUP BY ST_NAME                                        
          ORDER BY YEAR ASC ;

    -- write a sql query to find How many times has BJP gotten an Above 50% votes 
       SELECT COUNT(TOTVOTPOLL) AS VOTE_PERCENTAGE 
        FROM ELECTION 
          WHERE PARTYNAME='KARNATAKA' AND TOTVOTPOLL > 50 ;

  -- WRITE A SQL QUERY TO FIND what is the state list the BJP gets below 75% vote
     SELECT  COUNT(TOTVOTPOLL) AS VOTE_PERCENT_75
        FROM ELECTION 
            WHERE PARTYNAME='BJP' AND TOTVOTPOLL < 75 ;
        
    SELECT ST_NAME , COUNT(TOTVOTPOLL) AS VOTE_LESSTHAN_75
      FROM ELECTION
        WHERE PARTYNAME='TELANGANA' AND TOTVOTPOLL < 75 
          GROUP BY ST_NAME
            ORDER BY ST_NAME ASC ;

  
     
     -- WRITE A SQL QUERY TO DISPLAY THE BJP CANDIDATE LIST PARTICIPATED AT 
                 -- STATE ANDAMAN AND NICOBAR ISLANDS IN THE YEAR 1984
        
    SELECT CAND_NAME ,PARTYNAME,TOTVOTPOLL 
        FROM ELECTION 
           WHERE PARTYNAME='BJP' AND YEAR=1984 AND ST_NAME='Andaman & Nicoabar Islands';

    -- WRITE A SQL QUERY TO FIND HOW MANY MALE CANDIDATES PARTICIPATED IN ELECTION IN EACH STATE
    
    SELECT ST_NAME ,COUNT(ELECTORS) AS MALE_CANDIDATES
      FROM ELECTION 
          WHERE CAND_SEX='M' 
              GROUP BY ST_NAME;
    
    SELECT ST_NAME,CAND_NAME 
        FROM ELECTION
          WHERE CAND_SEX ='M' 
              ORDER BY ST_NAME ASC ;
     
     -- WRITE A SQL QUERY TO DISPLAY PARTY NAME IN DESCENDING ORDER 
     SELECT DISTINCT PARTYNAME 
        FROM ELECTION 
          ORDER BY PARTYNAME ASC;

     --WRITE A SQL QUERY TO FIND HOW MANY CANDIDATES PARTICIPATED IN WEST BENGAL IN THE YEAR 1988 
    
     SELECT ST_NAME,COUNT(ELECTORS) AS WEST_BENGAL_CANDIDATES
        FROM ELECTION 
          WHERE ST_NAME='West Bengal' AND YEAR=1988           -- WEST BENGAL STATE DATA NOT THERE IN THE DATABSE 
               GROUP BY ST_NAME
                  ORDER BY YEAR ASC;

     -- WRITE A SQL QUERY TO DISPLAY THE TAMILNADU CANDIDATE LIST IN EACH YEAR 

     SELECT DISTINCT YEAR,CAND_NAME 
      FROM ELECTION
         WHERE ST_NAME='Tamilnadu' 
            ORDER BY YEAR ASC;
                                   -- THERE IS NO STATE CALLED TAMILNADU 
                                          --SO WE REPLACE WITH BIHAR 
    SELECT DISTINCT YEAR,CAND_NAME 
      FROM ELECTION
        WHERE ST_NAME='KERALA'
           ORDER BY YEAR ASC;

     
     
     -- WRITE A SQL QUERY TO CALACULATE TOTAL VOTES BJP GOT IN BIHAR STATE IN THE YEAR 1996 

     SELECT SUM(TOTVOTPOLL) AS TOTAL_VOTES 
        FROM ELECTION
           WHERE ST_NAME= 'GUJARAT'  AND YEAR=1996 
              GROUP BY ST_NAME ;

     -- WRITE A SQL QUERY TO DISPLAY THE BJP CANDIDATES LIST IN DESCENDING ORDER 

     SELECT CAND_NAME 
        FROM ELECTION 
          WHERE PARTYNAME='BJP' 
              ORDER BY TOTVOTPOLL DESC ;
     
     
     SELECT TOTVOTPOLL,CAND_NAME 
        FROM ELECTION 
          WHERE PARTYNAME='BJP' 
              ORDER BY TOTVOTPOLL DESC ;
     
  -- WRITE AN SQL QUERY TO FIND HOW MANY TIMES  CONGRESS GETS ABOVE 50% IN BIHAR STATE 

  SELECT YEAR, COUNT(DISTINCT YEAR) VOTE_PERCENTAGE
    FROM ELECTION 
       WHERE ST_NAME='Bihar' AND PARTYNAME='Indian National Congress' AND TOTVOTPOLL > 50 
        GROUP BY YEAR ;

  -- WRITE A SQL QUERY TO FIND THE SIKKIM CANDIDATE LIST IN EACH YEAR 
 
  SELECT DISTINCT YEAR,CAND_NAME 
      FROM ELECTION                 -- NO DATA BELONGS TO SIKKIM IN THE GIVEN  DATABASE
        WHERE ST_NAME='SikkiM' ;

  -- WRITE A SQL QUERY TO FIND TOTAL MALE CANDIDATES PARTICIPATED IN ELECTION FROM EACH STATE
  
  SELECT DISTINCT(ST_NAME) ,COUNT(CAND_SEX) 
      FROM ELECTION 
        WHERE CAND_SEX='M' 
          GROUP BY  ST_NAME ;