-- describing the ELECTION table
DESC ELECTION;


-- TOTAL YEARS OF DATA AVAILABLE IN THE ELECTION TABLE
SELECT 
    DISTINCT(YEAR)
FROM
    ELECTION
ORDER BY YEAR;

-- TOTAL STATES AND UNION TERRITORIES  IN THE ELECTION TABLE AND STATE NAMES
--STATE COUNT
SELECT
    COUNT(DISTINCT(ST_NAME))
FROM
    ELECTION;

-- STATE NAMES
SELECT
    DISTINCT(ST_NAME)
FROM
    ELECTION;

-- TOTAL PARTIES AVAILABLE IN THE ELECTION DATA
SELECT 
    DISTINCT(PARTYNAME)
FROM
    ELECTION
ORDER BY 
    PARTYNAME;

--TOTAL PARTY ABBREVIATIONS AVAILABLE IN THE ELECTION TABLE
SELECT 
    DISTINCT(PARTYABBRE)
FROM
    ELECTION
ORDER BY 
    PARTYABBRE;


--------------------PERFORMANCE TUNING QUERIES ON ELECTION TABLE--------------------------------------------


-- total count of female candidates participating each year
SELECT 
    YEAR,
    COUNT(*) AS FEMALE_CANDIDATES
FROM 
    ELECTION
WHERE
    CAND_SEX = 'F'
GROUP BY 
    YEAR
ORDER BY 
    YEAR;


-- TOTAL CANDIDATES PARTICIPATED IN ELECTION AT EACH STATE IN EACH YEAR
SELECT 
    ST_NAME,
    YEAR,
    COUNT(*) AS TOTAL_CANDIDATES
FROM 
    ELECTION
GROUP BY
    ST_NAME,
    YEAR
ORDER BY
    ST_NAME,
    YEAR;

--TOTAL VOTES BJP GOT IN EACH STATE IN THE YEAR 1987
SELECT
    ST_NAME,
    SUM(TOTVOTPOLL) AS BJP_VOTES_OBTAINED,
    SUM(ELECTORS) AS TOTAL_VOTES
FROM
    ELECTION
GROUP BY 
    ST_NAME,
    YEAR,
    PARTYABBRE
HAVING
    PARTYABBRE = 'BJP' AND YEAR = 1984  -- no elections were held in the year 1987. hence we use the  year 1984
ORDER BY
    ST_NAME;
    
-- TOTAL CANDIDATES PARTITCIPATED IN ELECTION IN EACH STATE IN THE YEAR 2004
SELECT 
    ST_NAME,
    COUNT(*) AS TOTAL_CANDIDATES
FROM 
    ELECTION
GROUP BY 
    ST_NAME,
    YEAR
HAVING
    YEAR = 2004
ORDER BY 
    ST_NAME;

-- FETCH THE TOP 5 PARTIES THAT GOT THE MOST VOTES IN UTTAR PRADESH IN THE YEAR 2014
--In the database, only five state election details are provided, which does not include Uttar Prdesh
SELECT 
    PARTYNAME
FROM (
    SELECT 
        PARTYNAME, SUM(TOTVOTPOLL)AS VOTES
    FROM 
        ELECTION 
    WHERE 
        ST_NAME = 'Uttar Pradesh' AND YEAR = 2014  
    GROUP BY 
        PARTYNAME
)
ORDER BY VOTES DESC
FETCH FIRST 5 ROWS ONLY;



-- FETCH THE TOP 5 PARTIES THAT GOT THE MOST VOTES IN ANDHRA PRADESH IN THE YEAR 2014
SELECT 
    PARTYNAME
FROM (
    SELECT 
        PARTYNAME, SUM(TOTVOTPOLL)AS VOTES
    FROM 
        ELECTION 
    WHERE 
        ST_NAME = 'Andhra Pradesh' AND YEAR = 2014  
    GROUP BY 
        PARTYNAME
)
ORDER BY VOTES DESC
FETCH FIRST 5 ROWS ONLY;
