-- Election table
CREATE TABLE ELECTION (
    ST_NAME VARCHAR(30),
    YEAR NUMBER,
    PC_NO NUMBER,
    PC_NAME VARCHAR(50),
    PC_TYPE VARCHAR(15),
    CAND_NAME VARCHAR(50),
    CAND_SEX CHAR(2),
    PARTYNAME VARCHAR(10),
    PARTYABBRE VARCHAR(50),
    TOTVOTPOLL NUMBER,
    OBTVOTPOLL NUMBER
);

desc election;