--QUERY1

select YEAR,count(CAND_SEX) FROM voting WHERE 
CAND_SEX='F' GROUP BY YEAR;
-- QUERY2
SELECT COUNT(*) FROM VOTING GROUP BY ST_NAME,YEAR;

SELECT ST_NAME,YEAR,COUNT(*) FROM VOTING GROUP BY ST_NAME,YEAR;
--QUERY3
SELECT ST_NAME,SUM(TOTVOTPOLL)FROM VOTING WHERE YEAR=1987 AND PC_NAME='BJP' GROUP BY ST_NAME,CAND_NAME;
--QUERY4

SELECT ST_NAME,COUNT(*) FROM VOTING WHERE YEAR=2004 GROUP BY ST_NAME;

/*QUERY 5*/
SELECT PC_NAME FROM VOTING WHERE YEAR=2014 AND ST_NAME='Uttar Pradesh';

