
--to view the records in election
select * from election;

--to get the details of state names from records
select DISTINCT(st_name) from ELECTION;

--TO KNOW THE PARTYNAMES IN THE RECORD
SELECT DISTINCT(PARTYNAME) FROM ELECTION;

--TO KNOW HOW MANY YEARS ELECTIONS ARE HELD
SELECT DISTINCT(YEAR) FROM ELECTION;

-----------------------------------------------------------------------------------------------------------------------------
--                                     ***tuning preformance QUERIES***                                   --
-----------------------------------------------------------------------------------------------------------------------------
--total count of female candidates participating in each year
SELECT YEAR, COUNT(*) AS FEMALE_CANDIDATES
FROM ELECTION WHERE CAND_SEX='F'
GROUP BY YEAR ORDER BY YEAR;
 
-- TOTAL CANDIDATES PARTICIPATED AT EACH STATE IN EACH YEAR
SELECT ST_NAME, YEAR, COUNT(*) AS TOTAL_CANDIDATES
 FROM ELECTION 
 GROUP BY ST_NAME, YEAR;

--TOTAL VOTES BJP GOT IN EACH STATE IN YEAR 1987

SELECT ST_NAME,SUM(TOTVOTPOLL) AS TOTAL_VOTES
FROM ELECTION WHERE YEAR=1987 AND PARTYABBRE='BJP' 
GROUP BY ST_NAME, YEAR, PARTYABBRE
order by st_name;         -- 'no records found' will be result
                          -- as no election held in the year 1987

--total candidates participated in election in each state in the year 2004
SELECT ST_NAME, COUNT(*) AS TOTAL_CANDIDATES
FROM ELECTION 
GROUP BY ST_NAME, YEAR
HAVING YEAR= 2004 
ORDER BY ST_NAME;

/*SELECT ST_NAME, COUNT(*) AS TOTAL_CANDIDATES
FROM ELECTION WHERE YEAR=2004
GROUP BY ST_NAME
ORDER BY ST_NAME;
*/

--FETCH TOP 5 PARTIES THAT GOT THE MOST VOTES IN UTTAR PRADESH IN THE YEAR 2014
SELECT PARTYNAME 
FROM (SELECT PARTYNAME, SUM(TOTVOTPOLL) AS VOTES
      FROM ELECTION WHERE YEAR=2014 AND ST_NAME='Uttar Pradesh'
      GROUP BY PARTYNAME
    )ORDER BY VOTES DESC
    FETCH FIRST 5 ROWS ONLY;    --NO RECORDS HAS UTTAR PRADESH
------------------------------------------------------------------
-- EXTRA QUERIES 
------------------------------------------------------------------

--TO SELECT TOP 5 PARTIES THAT GOT THE MOST VOTES IN ANDHRA PRADESH IN THE YEAR 1980
SELECT PARTYNAME, VOTES
FROM (SELECT PARTYNAME, SUM(TOTVOTPOLL) AS VOTES
      FROM ELECTION WHERE YEAR=1980 AND ST_NAME='Andhra Pradesh'
      GROUP BY PARTYNAME
    )ORDER BY VOTES DESC
    FETCH FIRST 5 ROWS ONLY;
    

--      **SET1**
--TOTAL CANDIDATES PARTICIPATED IN EACH STATE IN YEAR 2004
SELECT ST_NAME,COUNT(*) AS TOTAL_CANDIDATES
FROM ELECTION 
GROUP BY ST_NAME, YEAR
HAVING YEAR=2004;

--TOTAL FEMALE CANDIDATES PARTICIPATED IN EACH YEAR
SELECT YEAR, COUNT(*)
FROM ELECTION
GROUP BY YEAR, CAND_SEX
HAVING CAND_SEX='F';

--TOTAL CANDIDATES PARTICIPATED IN WEST BENGAL IN YEAR 2014
SELECT COUNT(*) FROM ELECTION
WHERE ST_NAME='WEST BENGAL' AND YEAR=2014; -- NO RECORDS WITH STATE WEST BENGAL

--TOTAL VOTES BJP GOT IN ANDHRA PRADESH IN THE YEAR 1987
SELECT SUM(TOTVOTPOLL) FROM ELECTION 
WHERE PARTYABBRE='BJP', ST_NAME='ANDHRA PRADESH', YEAR=1987; 

