
SELECT * FROM VOTING;

select YEAR,count(CAND_SEX) FROM voting WHERE 
CAND_SEX='F' GROUP BY YEAR;

SELECT COUNT(*) FROM VOTING GROUP BY ST_NAME,YEAR;

SELECT ST_NAME,YEAR,COUNT(*) FROM VOTING GROUP BY ST_NAME,YEAR;

SELECT ST_NAME,SUM(TOTVOTPOLL)FROM VOTING WHERE YEAR=1987 AND PC_NAME='BJP' GROUP BY ST_NAME, CAND_NAME;