-- describing the voting table
DESC VOTING;

-- TOTAL YEARS OF DATA AVAILABLE IN THE VOTING TABLE
SELECT 
    DISTINCT(YEAR)
FROM 
    VOTING
ORDER BY YEAR;

-- TOTAL STATES AND UNION TERRITORIES  IN THE VOTING TABLE AND STATE NAMES
--STATE COUNT
SELECT
    COUNT(DISTINCT(ST_NAME))
FROM
    VOTING;

-- STATE NAMES
SELECT
    DISTINCT(ST_NAME)
FROM
    VOTING;

-- TOTAL PARTIES AVAILABLE IN THE VOTING DATA
SELECT 
    DISTINCT(PARTYNAME)
FROM
    VOTING
ORDER BY 
    PARTYNAME;

--TOTAL PARTY ABBREVIATIONS AVAILABLE IN THE VOTING TABLE
SELECT 
    DISTINCT(PARTYABBRE)
FROM
    VOTING
ORDER BY 
    PARTYABBRE;



-- PERFORMANCE TUNING QUERIES ON VOTING TABLE
-- total count of female candidates participating each year
SELECT 
    YEAR,
    COUNT(*) AS FEMALE_CANDIDATES
FROM 
    VOTING
WHERE
    CAND_SEX = 'F'
GROUP BY 
    YEAR
ORDER BY 
    YEAR;


-- TOTAL CANDIDATES PARTICIPATED IN ELECTION AT EACH STATE IN EACH YEAR
SELECT 
    ST_NAME,
    YEAR,
    COUNT(*) AS TOTAL_CANDIDATES
FROM 
    VOTING
GROUP BY
    ST_NAME,
    YEAR
ORDER BY
    ST_NAME,
    YEAR;

--TOTAL VOTES BJP GOT IN EACH STATE IN THE YEAR 1987
SELECT
    ST_NAME,
    SUM(TOTVOTPOLL) AS VOTES_OBTAINED,
    SUM(ELECTORS) AS TOTAL_VOTES
FROM
    VOTING
GROUP BY 
    ST_NAME,
    YEAR,
    PARTYABBRE
HAVING
    PARTYABBRE = 'BJP' AND YEAR = 1984  -- no elections were held in the year 1987. hence we use the  year 1984
ORDER BY
    ST_NAME;
